import Foundation

/// Stateful multi-turn conversation wrapper for agent interaction.
///
/// `Conversation` maintains message history across multiple turns,
/// enabling stateful chat-like interactions with an agent. Each message
/// sent by the user and each response from the assistant is stored,
/// creating a complete transcript of the dialogue.
///
/// ## Overview
///
/// Use `Conversation` when you need to maintain context across multiple
/// exchanges with an agent. Unlike one-off `AgentRuntime.run()` calls,
/// conversation automatically includes previous messages in subsequent
/// requests, allowing the agent to reference earlier parts of the discussion.
///
/// ## Usage
///
/// Create a conversation with an agent:
///
/// ```swift
/// let conversation = Conversation(with: agent)
///
/// // First turn
/// let response1 = try await conversation.send("What is Swift?")
/// print(response1.output)
///
/// // Second turn (includes history from first)
/// let response2 = try await conversation.send("How does concurrency work?")
/// // The agent can reference "Swift" from the first message
/// ```
///
/// ## Conversation State
///
/// The conversation stores:
/// - All user messages
/// - All assistant responses
/// - Tool call history (via the underlying runtime)
///
/// This history is automatically included in subsequent calls to ``send(_:)``
/// or ``stream(_:)``.
///
/// ## Relationship to Other Types
///
/// - ``AgentRuntime``: The underlying runtime that processes each turn
/// - ``Session``: Optional persisted storage for conversation history
/// - ``AgentObserver``: Optional callback receiver for lifecycle events
///
/// ## Topics
///
/// ### Creating Conversations
/// - ``init(with:session:observer:)``
///
/// ### Sending Messages
/// - ``send(_:)``
/// - ``stream(_:)``
/// - ``streamText(_:)``
///
/// ### Accessing History
/// - ``messages``
/// - ``Message``
///
/// ### Observing Events
/// - ``observer``
///
/// ### Branching Conversations
/// - ``branch()``
public actor Conversation {
    /// A single message in a conversation transcript.
    ///
    /// `Message` represents one turn in the conversation, either from
    /// the user or the assistant. Messages are immutable and can be
    /// safely shared across concurrency domains.
    ///
    /// ## Example
    ///
    /// ```swift
    /// let userMessage = Message(role: .user, text: "Hello!")
    /// let assistantMessage = Message(role: .assistant, text: "Hi there!")
    /// ```
    ///
    /// ## Topics
    ///
    /// ### Creating Messages
    /// - ``init(role:text:)``
    ///
    /// ### Message Properties
    /// - ``role``
    /// - ``text``
    ///
    /// ### Message Roles
    /// - ``Role``
    public struct Message: Sendable, Equatable {
        /// The role of a participant in a conversation.
        ///
        /// `Role` identifies whether a message was sent by the user
        /// or generated by the assistant.
        ///
        /// ## Cases
        ///
        /// ### `user`
        /// A message sent by the end user.
        ///
        /// ```swift
        /// let message = Message(role: .user, text: "What's the weather?")
        /// ```
        ///
        /// ### `assistant`
        /// A response generated by the AI assistant.
        ///
        /// ```swift
        /// let message = Message(role: .assistant, text: "It's sunny today.")
        /// ```
        public enum Role: String, Sendable {
            /// The end user sending messages to the agent.
            case user
            
            /// The AI assistant generating responses.
            case assistant
        }

        /// The role of the message sender.
        ///
        /// Indicates whether this message was sent by the ``user``
        /// or the ``assistant``.
        public let role: Role
        
        /// The text content of the message.
        ///
        /// For user messages, this is the input text. For assistant
        /// messages, this is the generated response text.
        public let text: String

        /// Creates a new message with the specified role and text.
        ///
        /// - Parameters:
        ///   - role: The role of the message sender (``user`` or ``assistant``)
        ///   - text: The text content of the message
        ///
        /// ## Example
        ///
        /// ```swift
        /// let message = Message(role: .user, text: "Hello, assistant!")
        /// ```
        public init(role: Role, text: String) {
            self.role = role
            self.text = text
        }
    }

    /// The conversation history as an array of messages.
    ///
    /// This property provides read-only access to all messages in the
    /// conversation, in chronological order. The array includes both
    /// user messages and assistant responses.
    ///
    /// ## Example
    ///
    /// ```swift
    /// let conversation = Conversation(with: agent)
    /// try await conversation.send("Hello")
    /// try await conversation.send("How are you?")
    ///
    /// // Access the transcript
    /// for message in await conversation.messages {
    ///     print("\(message.role): \(message.text)")
    /// }
    /// ```
    ///
    /// ## Note
    ///
    /// Messages are appended automatically when using ``send(_:)``,
    /// ``stream(_:)``, or ``streamText(_:)``. You cannot manually
    /// modify this array; use the provided methods to interact with
    /// the conversation.
    public var messages: [Message] {
        _messages
    }

    /// An optional observer for agent lifecycle events.
    ///
    /// Set this property to receive callbacks during agent execution,
    /// such as when the agent starts processing, completes a turn,
    /// or encounters an error.
    ///
    /// ## Example
    ///
    /// ```swift
    /// let conversation = Conversation(with: agent)
    /// conversation.observer = MyAgentObserver()
    ///
    /// // The observer will receive callbacks for each send()
    /// let response = try await conversation.send("Hello")
    /// ```
    ///
    /// ## See Also
    ///
    /// - ``AgentObserver``
    public var observer: (any AgentObserver)?

    private let agent: any AgentRuntime
    private let session: (any Session)?
    private var _messages: [Message] = []

    /// Creates a new conversation with the specified agent.
    ///
    /// Use this initializer to create a conversation that wraps an agent
    /// runtime. The conversation will manage message history and can
    /// optionally use a session for persisted storage.
    ///
    /// - Parameters:
    ///   - agent: The agent runtime to use for processing messages
    ///   - session: An optional session for persisting conversation history.
    ///     If provided, the session may be used by the agent to store
    ///     additional context beyond the message transcript.
    ///   - observer: An optional observer to receive lifecycle callbacks
    ///     during agent execution
    ///
    /// ## Example
    ///
    /// ```swift
    /// // Basic conversation
    /// let conversation = Conversation(with: agent)
    ///
    /// // With a session for persistence
    /// let session = MySession()
    /// let conversation = Conversation(
    ///     with: agent,
    ///     session: session
    /// )
    ///
    /// // With an observer
    /// let conversation = Conversation(
    ///     with: agent,
    ///     observer: MyObserver()
    /// )
    ///
    /// // With both session and observer
    /// let conversation = Conversation(
    ///     with: agent,
    ///     session: session,
    ///     observer: MyObserver()
    /// )
    /// ```
    ///
    /// ## See Also
    ///
    /// - ``AgentRuntime``
    /// - ``Session``
    /// - ``AgentObserver``
    public init(with agent: some AgentRuntime, session: (any Session)? = nil, observer: (any AgentObserver)? = nil) {
        self.init(agent: agent, session: session, observer: observer, messages: [])
    }

    init(
        agent: any AgentRuntime,
        session: (any Session)?,
        observer: (any AgentObserver)?,
        messages: [Message]
    ) {
        self.agent = agent
        self.session = session
        self.observer = observer
        _messages = messages
    }

    /// Sends a user message and returns the complete agent response.
    ///
    /// This method appends the user message to the conversation history,
    /// runs the agent with the current context (including all previous
    /// messages), and appends the assistant's response to the history.
    ///
    /// - Parameter input: The user's message text to send
    /// - Returns: The complete result from the agent, including output
    ///   text and any tool calls or metadata
    /// - Throws: An error if the agent fails to process the message
    ///
    /// ## Example
    ///
    /// ```swift
    /// let conversation = Conversation(with: agent)
    ///
    /// // First turn
    /// let result1 = try await conversation.send("What is Swift?")
    /// print(result1.output)
    ///
    /// // Second turn (includes context from first)
    /// let result2 = try await conversation.send("What are its main features?")
    /// // The agent understands "its" refers to Swift
    /// ```
    ///
    /// ## Note
    ///
    /// This method is marked with `@discardableResult` because you may
    /// not need the result if you only care about the text output
    /// (which is also stored in ``messages``). However, the result
    /// contains additional metadata that may be useful.
    @discardableResult
    public func send(_ input: String) async throws -> AgentResult {
        _messages.append(.init(role: .user, text: input))
        let result = try await agent.run(input, session: session, observer: observer)
        _messages.append(.init(role: .assistant, text: result.output))
        return result
    }

    /// Streams agent events for a user message.
    ///
    /// This method provides true streaming of agent events, allowing you
    /// to receive and process events as they occur during agent execution.
    /// Unlike ``send(_:)``, this method does not automatically update the
    /// conversation's message history.
    ///
    /// - Parameter input: The user's message text to send
    /// - Returns: An async stream of agent events (tokens, chunks, lifecycle events)
    ///
    /// ## Example
    ///
    /// ```swift
    /// let conversation = Conversation(with: agent)
    ///
    /// for try await event in conversation.stream("Tell me a story") {
    ///     switch event {
    ///     case .output(.token(let token)):
    ///         print(token, terminator: "")
    ///     case .lifecycle(.completed(let result)):
    ///         print("\nCompleted with: \(result.output)")
    ///     case .lifecycle(.failed(let error)):
    ///         print("Error: \(error)")
    ///     default:
    ///         break
    ///     }
    /// }
    /// ```
    ///
    /// ## Important
    ///
    /// This method does **not** automatically append messages to the
    /// conversation history. If you want to update the transcript,
    /// you must manually append the messages or use ``streamText(_:)``
    /// instead.
    ///
    /// ## See Also
    ///
    /// - ``AgentEvent``
    /// - ``streamText(_:)``
    public nonisolated func stream(_ input: String) -> AsyncThrowingStream<AgentEvent, Error> {
        agent.stream(input, session: session, observer: nil)
    }

    /// Streams the text response for a user message.
    ///
    /// This method streams the agent's response and collects the text output,
    /// appending both the user message and the complete assistant response
    /// to the conversation history. It's a convenience method that combines
    /// streaming with automatic history management.
    ///
    /// - Parameter input: The user's message text to send
    /// - Returns: The complete text response from the agent
    /// - Throws: An error if streaming fails
    ///
    /// ## Example
    ///
    /// ```swift
    /// let conversation = Conversation(with: agent)
    ///
    /// // Stream and collect the response
    /// let response = try await conversation.streamText("Write a poem")
    /// print(response)
    ///
    /// // The conversation history is updated automatically
    /// for message in await conversation.messages {
    ///     print("\(message.role): \(message.text)")
    /// }
    /// ```
    ///
    /// ## How It Works
    ///
    /// This method:
    /// 1. Appends the user message to history
    /// 2. Streams events from the agent
    /// 3. Collects token and chunk events into a final string
    /// 4. Appends the assistant's response to history
    /// 5. Returns the complete text
    ///
    /// ## See Also
    ///
    /// - ``stream(_:)`` - For access to individual events
    @discardableResult
    public func streamText(_ input: String) async throws -> String {
        _messages.append(.init(role: .user, text: input))

        var final = ""
        for try await event in agent.stream(input, session: session, observer: observer) {
            switch event {
            case .output(.token(let token)):
                final += token
            case .output(.chunk(let chunk)):
                final += chunk
            case .lifecycle(.completed(let result)):
                if final.isEmpty {
                    final = result.output
                }
            default:
                break
            }
        }

        _messages.append(.init(role: .assistant, text: final))
        return final
    }

    /// Creates an isolated branch of the current conversation state.
    ///
    /// Branching creates a new ``Conversation`` that starts with the same
    /// transcript and observer as the current conversation. This is useful
    /// when you want to explore different paths from a common starting point
    /// without affecting the original conversation.
    ///
    /// When the wrapped runtime supports native branching
    /// (``ConversationBranchingRuntime``), its execution state is forked
    /// as well. Otherwise, Swarm branches by cloning the conversation session.
    ///
    /// - Returns: A new ``Conversation`` with the same initial state
    /// - Throws: An error if branching fails
    ///
    /// ## Example
    ///
    /// ```swift
    /// let mainConversation = Conversation(with: agent)
    /// try await mainConversation.send("What programming language should I learn?")
    ///
    /// // Branch to explore Python path
    /// let pythonBranch = try await mainConversation.branch()
    /// try await pythonBranch.send("Tell me about Python")
    ///
    /// // Branch to explore Swift path
    /// let swiftBranch = try await mainConversation.branch()
    /// try await swiftBranch.send("Tell me about Swift")
    ///
    /// // Main conversation is unchanged
    /// // pythonBranch and swiftBranch have independent histories
    /// ```
    ///
    /// ## Use Cases
    ///
    /// - **Exploring alternatives**: Try different approaches from a checkpoint
    /// - **Parallel processing**: Process multiple variations simultaneously
    /// - **Undo/redo**: Save conversation state before risky operations
    /// - **A/B testing**: Compare agent behavior with different follow-ups
    ///
    /// ## See Also
    ///
    /// - ``ConversationBranchingRuntime``
    /// - ``ConversationBranchingSession``
    public func branch() async throws -> Conversation {
        let branchedAgent: any AgentRuntime
        if let branchingRuntime = agent as? any ConversationBranchingRuntime {
            branchedAgent = try await branchingRuntime.branchConversationRuntime()
        } else {
            branchedAgent = agent
        }

        let branchedSession = try await Self.branchSession(session)
        return Conversation(
            agent: branchedAgent,
            session: branchedSession,
            observer: observer,
            messages: _messages
        )
    }

    private static func branchSession(_ session: (any Session)?) async throws -> (any Session)? {
        guard let session else {
            return nil
        }

        if let branchingSession = session as? any ConversationBranchingSession {
            return try await branchingSession.branchConversationSession()
        }

        let branched = InMemorySession()
        let items = try await session.getAllItems()
        try await branched.addItems(items)
        return branched
    }
}
