// MemoryMessage.swift
// Swarm Framework
//
// Core message type for agent memory systems.

import Foundation

// MARK: - MemoryMessage

/// Represents a single message in agent memory.
///
/// `MemoryMessage` is the fundamental unit of conversation history,
/// storing the role, content, and metadata for each interaction.
/// Messages are immutable value types, ensuring safe sharing across
/// concurrent contexts.
///
/// ## Message Roles
///
/// Every message has a ``Role`` indicating who sent it:
///
/// | Role | Description | Typical Use |
/// |------|-------------|-------------|
/// | ``Role/user`` | Human user input | Questions, commands, responses |
/// | ``Role/assistant`` | AI assistant output | Answers, completions, thoughts |
/// | ``Role/system`` | System instructions | Persona, constraints, context |
/// | ``Role/tool`` | Tool execution results | Function outputs, API responses |
///
/// ## Creating Messages
///
/// Use the convenience factory methods for common cases:
///
/// ```swift
/// // User message
/// let userMsg = MemoryMessage.user("What's the weather?")
///
/// // Assistant response
/// let assistantMsg = MemoryMessage.assistant("The weather is sunny.")
///
/// // System instruction
/// let systemMsg = MemoryMessage.system("You are a helpful assistant.")
///
/// // Tool result
/// let toolMsg = MemoryMessage.tool(
///     "{\"temperature\": 72}",
///     toolName: "get_weather"
/// )
/// ```
///
/// ## Adding Metadata
///
/// Attach metadata to messages for additional context:
///
/// ```swift
/// let message = MemoryMessage.user(
///     "Hello",
///     metadata: [
///         "source": "mobile_app",
///         "user_id": "user-123",
///         "language": "en"
///     ]
/// )
/// ```
///
/// ## Storing in Memory
///
/// Messages are added to a ``Memory`` implementation:
///
/// ```swift
/// let memory: ConversationMemory = .conversation(maxMessages: 100)
/// await memory.add(MemoryMessage.user("Hello!"))
/// await memory.add(MemoryMessage.assistant("Hi there!"))
/// ```
///
/// - SeeAlso: ``Memory``, ``Memory/Role``
public struct MemoryMessage: Sendable, Codable, Identifiable, Equatable, Hashable {
    /// The role of the entity in a conversation.
    ///
    /// The role indicates who sent a message and influences how the
    /// message is processed by the AI model.
    ///
    /// ## Roles
    ///
    /// ### User
    /// ```swift
    /// MemoryMessage.user("What's the capital of France?")
    /// ```
    /// Represents input from the human user. This is the most common
    /// role for incoming messages.
    ///
    /// ### Assistant
    /// ```swift
    /// MemoryMessage.assistant("The capital of France is Paris.")
    /// ```
    /// Represents output from the AI assistant. These messages are
    /// typically generated by the LLM and stored after completion.
    ///
    /// ### System
    /// ```swift
    /// MemoryMessage.system("You are a helpful travel assistant.")
    /// ```
    /// Represents system-level instructions that guide the assistant's
    /// behavior, persona, or constraints. Not all models support system
    /// messages in conversation history.
    ///
    /// ### Tool
    /// ```swift
    /// MemoryMessage.tool(
    ///     "{\"result\": 42}",
    ///     toolName: "calculate"
    /// )
    /// ```
    /// Represents output from tool or function executions. These
    /// messages typically contain structured data or API responses.
    ///
    /// - SeeAlso: ``MemoryMessage/user(_:metadata:)``,
    ///   ``MemoryMessage/assistant(_:metadata:)``,
    ///   ``MemoryMessage/system(_:metadata:)``,
    ///   ``MemoryMessage/tool(_:toolName:)``
    public enum Role: String, Sendable, Codable, CaseIterable {
        /// Message from the user/human.
        ///
        /// Represents input provided by the end user. This is the
        /// primary role for conversation input.
        case user

        /// Message from the AI assistant.
        ///
        /// Represents responses generated by the AI model. These
        /// messages are typically stored after receiving a completion
        /// from the LLM.
        case assistant

        /// System instruction or context.
        ///
        /// Provides high-level instructions that guide the assistant's
        /// behavior, persona, or constraints throughout the conversation.
        /// Note: Not all models support system messages in history.
        case system

        /// Output from a tool execution.
        ///
        /// Represents results from function calls or external API
        /// invocations. The `tool_name` metadata field typically
        /// contains the name of the invoked tool.
        case tool
    }

    /// Unique identifier for this message.
    ///
    /// Automatically generated as a UUID when the message is created.
    /// Use this ID to track, reference, or deduplicate messages.
    public let id: UUID

    /// The role of the entity that produced this message.
    ///
    /// Indicates whether this message is from the user, assistant,
    /// system, or a tool. See ``Role`` for details on each role.
    public let role: Role

    /// The textual content of the message.
    ///
    /// The actual message text. For tool messages, this may be
    /// JSON or other structured data.
    public let content: String

    /// When this message was created.
    ///
    /// Automatically set to the current date/time when the message
    /// is created. Useful for sorting, filtering, or displaying
    /// conversation history.
    public let timestamp: Date

    /// Additional key-value metadata attached to this message.
    ///
    /// Use metadata to store application-specific information such as:
    /// - Source platform (web, mobile, API)
    /// - User identifiers
    /// - Message language
    /// - Tool names (for tool messages)
    /// - Custom tags
    ///
    /// ## Example
    ///
    /// ```swift
    /// let message = MemoryMessage(
    ///     role: .user,
    ///     content: "Hello",
    ///     metadata: ["source": "mobile_app", "version": "2.1"]
    /// )
    /// ```
    public let metadata: [String: String]

    /// Formatted content including role prefix for context display.
    ///
    /// Returns a formatted string suitable for inclusion in prompts
    /// or conversation displays:
    ///
    /// ```
    /// [user]: What's the weather?
    /// [assistant]: It's sunny today.
    /// ```
    ///
    /// This format is used by ``MemoryMessage/formatContext(_:tokenLimit:tokenEstimator:)``
    /// when building context strings for LLM prompts.
    public var formattedContent: String {
        "[\(role.rawValue)]: \(content)"
    }

    /// Creates a new memory message.
    ///
    /// Use the convenience factory methods (``user(_:metadata:)``,
    /// ``assistant(_:metadata:)``, etc.) for common cases instead
    /// of this initializer.
    ///
    /// - Parameters:
    ///   - id: Unique identifier (defaults to new UUID).
    ///   - role: The role of the message sender.
    ///   - content: The message content.
    ///   - timestamp: When the message was created (defaults to now).
    ///   - metadata: Additional key-value metadata.
    public init(
        id: UUID = UUID(),
        role: Role,
        content: String,
        timestamp: Date = Date(),
        metadata: [String: String] = [:]
    ) {
        self.id = id
        self.role = role
        self.content = content
        self.timestamp = timestamp
        self.metadata = metadata
    }
}

// MARK: - Convenience Factory Methods

public extension MemoryMessage {
    /// Creates a user message.
    ///
    /// User messages represent input from the human end user.
    ///
    /// ## Example
    ///
    /// ```swift
    /// let message = MemoryMessage.user("What's the weather like?")
    /// await memory.add(message)
    /// ```
    ///
    /// ## With Metadata
    ///
    /// ```swift
    /// let message = MemoryMessage.user(
    ///     "Book a flight",
    ///     metadata: ["intent": "book_flight", "urgency": "high"]
    /// )
    /// ```
    ///
    /// - Parameters:
    ///   - content: The message content from the user.
    ///   - metadata: Optional key-value metadata for application-specific data.
    /// - Returns: A new message with ``Role/user`` role.
    static func user(_ content: String, metadata: [String: String] = [:]) -> MemoryMessage {
        MemoryMessage(role: .user, content: content, metadata: metadata)
    }

    /// Creates an assistant message.
    ///
    /// Assistant messages represent responses from the AI model.
    ///
    /// ## Example
    ///
    /// ```swift
    /// let response = await model.generate(for: prompt)
    /// let message = MemoryMessage.assistant(response)
    /// await memory.add(message)
    /// ```
    ///
    /// ## With Metadata
    ///
    /// ```swift
    /// let message = MemoryMessage.assistant(
    ///     "The weather is sunny.",
    ///     metadata: ["model": "gpt-4", "tokens": "150"]
    /// )
    /// ```
    ///
    /// - Parameters:
    ///   - content: The assistant's response content.
    ///   - metadata: Optional key-value metadata for application-specific data.
    /// - Returns: A new message with ``Role/assistant`` role.
    static func assistant(_ content: String, metadata: [String: String] = [:]) -> MemoryMessage {
        MemoryMessage(role: .assistant, content: content, metadata: metadata)
    }

    /// Creates a system message.
    ///
    /// System messages provide high-level instructions that guide the
    /// assistant's behavior throughout the conversation.
    ///
    /// ## Example
    ///
    /// ```swift
    /// let persona = MemoryMessage.system(
    ///     "You are a helpful travel assistant specializing in European destinations."
    /// )
    /// await memory.add(persona)
    /// ```
    ///
    /// ## Common Uses
    ///
    /// - Setting the assistant's persona or personality
    /// - Defining constraints (e.g., "Be concise")
    /// - Providing context about the user
    /// - Specifying output formats
    ///
    /// > Note: Not all LLM providers support system messages in conversation
    /// > history. Some only accept a single system message at the start.
    ///
    /// - Parameters:
    ///   - content: The system instruction or context.
    ///   - metadata: Optional key-value metadata for application-specific data.
    /// - Returns: A new message with ``Role/system`` role.
    static func system(_ content: String, metadata: [String: String] = [:]) -> MemoryMessage {
        MemoryMessage(role: .system, content: content, metadata: metadata)
    }

    /// Creates a tool result message.
    ///
    /// Tool messages represent output from function calls, API requests,
    /// or other external tool executions.
    ///
    /// ## Example
    ///
    /// ```swift
    /// let result = try await weatherAPI.fetch(city: "Paris")
    /// let message = MemoryMessage.tool(
    ///     result.jsonString,
    ///     toolName: "get_weather"
    /// )
    /// await memory.add(message)
    /// ```
    ///
    /// The `toolName` is automatically added to the message metadata
    /// under the key `"tool_name"`, making it easy to track which
    /// tool produced each result.
    ///
    /// ## Structured Data
    ///
    /// Tool content is often JSON or other structured formats:
    ///
    /// ```swift
    /// let json = """
    /// {"temperature": 72, "unit": "F", "condition": "sunny"}
    /// """
    /// let message = MemoryMessage.tool(json, toolName: "get_weather")
    /// ```
    ///
    /// - Parameters:
    ///   - content: The tool output content (often JSON or structured data).
    ///   - toolName: The name of the tool that produced this result.
    /// - Returns: A new message with ``Role/tool`` role and `tool_name` metadata.
    static func tool(_ content: String, toolName: String) -> MemoryMessage {
        MemoryMessage(role: .tool, content: content, metadata: ["tool_name": toolName])
    }
}

// MARK: CustomStringConvertible

extension MemoryMessage: CustomStringConvertible {
    /// A human-readable description of the message.
    ///
    /// Truncates long content for readability:
    ///
    /// ```
    /// MemoryMessage(user: "Hello, how are you...")
    /// MemoryMessage(assistant: "I'm doing well...")
    /// ```
    public var description: String {
        "MemoryMessage(\(role.rawValue): \"\(content.prefix(50))\(content.count > 50 ? "..." : "")\")"
    }
}
